NET6.Web/ViewComponents/CssViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace NET6.Web.ViewComponents
{
    public class CssViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

NET6.Web/ViewComponents/HomeCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NET6.Service.Services.Abstractions;

namespace NET6.Web.ViewComponents
{
    public class HomeCategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;

        public HomeCategoriesViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await categoryService.GetAllCategoriesNonDeletedTake24();
            return View(categories);
        }
    }
}

NET6.Web/ViewComponents/ScriptViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace NET6.Web.ViewComponents
{
    public class ScriptViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }

}

NET6.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en" class="no-js classic-page-layout " data-audio-tick="~/PlainHtml/audio/tick.mp3" data-click-ripple-animation="yes">
<head>
    @await Component.InvokeAsync("Css")
</head>
<body>
    <div id="page" class="hfeed site">

        <!-- .site-main -->
        <main id="main" class="site-main cd-main">
         

            <div class="site-middle">
                <div class="layout-medium">
                    <div id="primary" class="content-area with-sidebar">
                        @RenderBody()
                    </div>
                    <!-- #secondary -->
                    <div id="secondary" class="widget-area sidebar" role="complementary">


                        <!-- widget : categories -->
                        <aside class="widget widget_categories">
                            <h3 class="widget-title">Categories</h3>
                            @await Component.InvokeAsync("HomeCategories")

                        </aside>

                        <!-- widget : popular-posts -->
                        <!-- widget : text -->
                        <aside class="widget widget_text">
                            <!--<h3 class="widget-title">Advertisement</h3>-->
                            <div class="textwidget">
                                <a href="#"><img src="~/PlainHtml/images/blog/banner.jpg" alt="banner"></a>
                            </div>
                        </aside>
                        <!-- widget : text -->

                    </div>
                </div>
            </div>
            <!-- #secondary -->

        </main>
    </div>




    <!-- ALERT : used for contact form mail delivery alert -->
    <div class="site-alert animated"></div>
    <!-- .site-footer -->
    <footer id="colophon" class="site-footer" role="contentinfo">

        <!-- .site-info -->
        <div class="site-info">
            <div class="textwidget">
                <p><a href="http://pixelwars.org/">Copyright &copy; 2017 by Pixelwars</a></p>
            </div>
        </div>
        <!-- .site-info -->

    </footer>
    <!-- .site-footer -->
    <a href="#" id="back-to-top" class="show">↑ <span>Scroll to top</span></a>

    @await Component.InvokeAsync("Script")
</body>
</html>

NET6.Web/Views/Shared/_LayoutError.cshtml
<!DOCTYPE html>
<html
<head>
     <link rel="stylesheet" href="~/css/style.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" />

</head>

<body>
    <section class="page_404">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    @RenderBody();
                </div>
            </div>
        </div>
    </section>
</body>
</html>